import createCollection from '@/shared/lib/createCollection';

// categorias holds category ids
const useSuppliers = createCollection('suppliers', [
  {
    id: 1,
    name: 'Textiles Bogotá S.A.S.',
    iva: 19,
    tipoDocumento: 'NIT',
    documento: '900123456-1',
    contacto: 'Pedro Vargas',
    email: 'pvargas@textilesbog.com',
    tel: '601-234-5678',
    direccion: 'Cra 13 # 45-20, Chapinero',
    ciudad: 'Bogotá',
    categorias: [1, 4, 2],
    estado: 'Activo',
  },
  {
    id: 2,
    name: 'ModaCali S.A.',
    iva: 19,
    tipoDocumento: 'NIT',
    documento: '800234567-2',
    contacto: 'Sandra Lozano',
    email: 'slozano@modacali.com',
    tel: '602-345-6789',
    direccion: 'Calle 5 # 38-25, San Fernando',
    ciudad: 'Cali',
    categorias: [2, 3],
    estado: 'Activo',
  },
  {
    id: 3,
    name: 'DenimCo',
    iva: 0,
    tipoDocumento: 'NIT',
    documento: '901345678-3',
    contacto: 'Ricardo Montoya',
    email: 'r.montoya@denimco.co',
    tel: '604-456-7890',
    direccion: 'CL 48 # 53-62, CC Venaver piso 10',
    ciudad: 'Medellín',
    categorias: [3],
    estado: 'Activo',
  },
  {
    id: 4,
    name: 'LuxFashion Ltda.',
    iva: 19,
    tipoDocumento: 'NIT',
    documento: '830456789-4',
    contacto: 'Andrea Silva',
    email: 'asilva@luxfashion.com',
    tel: '605-567-8901',
    direccion: 'Av. Calle 80 # 69-70, Bodega 4',
    ciudad: 'Bogotá',
    categorias: [5, 6],
    estado: 'Activo',
  },
  {
    id: 5,
    name: 'KnitCo Textiles',
    iva: 0,
    tipoDocumento: 'NIT',
    documento: '900567890-5',
    contacto: 'Jorge Pérez',
    email: 'jperez@knitco.co',
    tel: '607-678-9012',
    direccion: 'Cra 23 # 64-15, Cable Plaza',
    ciudad: 'Manizales',
    categorias: [6],
    estado: 'Inactivo',
  },
  {
    id: 6,
    name: 'GlamourBtq',
    iva: 0,
    tipoDocumento: 'NIT',
    documento: '901678901-6',
    contacto: 'Lucía Ramírez',
    email: 'lucia@glamourbtq.co',
    tel: '601-876-5432',
    direccion: 'Calle 72 # 10-34, Local 102',
    ciudad: 'Bogotá',
    categorias: [7],
    estado: 'Activo',
  },
]);

export default useSuppliers;
